name: "Build + test"
on:
  pull_request:
  push:
    branches: [main]
permissions:
  contents: read
  pull-requests: write
jobs:
  qnas:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
      - name: Free disk space
        if: false
        run: |
          df -h
          sudo docker image prune --all --force || true
          df -h
          sudo rm -rf "$AGENT_TOOLSDIRECTORY" || true
          df -h
          sudo rm -rf /usr/local/lib/android || true
          df -h
          sudo rm -rf /usr/share/dotnet || true
          df -h
          sudo swapoff -a || true
          sudo rm -f /mnt/swapfile || true
          df -h
      - uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31.9.0
        with:
          enable_kvm: true
          extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
      - uses: cachix/cachix-action@v15
        with:
          name: ts433
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build qnas system
        run: |
          nix build .#nixosConfigurations.qnas.config.system.build.toplevel -o result-current
